### ISSUE TITLE
Docker file for the prebuilt Docker image

### ISSUE THREAD

**Issue by QuyANgo** [TissueImageAnalytics/tiatoolbox-docker#6]
Hello,

I'd like to add pyvips into the Docker image. Would it be possible for you to share the Docker file that was used to build the Docker image here?

Many thanks in advance!

**Comment by shaneahmed** [comment]
You can access these here https://github.com/TissueImageAnalytics/tiatoolbox/blob/develop/.github/workflows/docker-publish.yml
